### ISSUE TITLE
Executar...

### ISSUE THREAD

**Issue by rregio** [Takasakiii/notas-univesp-2022#1]
como executa??? quero executar isso aí... dá pra prever a nota??

**Comment by Takasakiii** [comment]
Sim da para calcular tanto a media normal, tanto quanto você precisa tirar na prova

deixarei anexado tambem uma build para pcs windows, para vc rodar, basta executar o exe
[notas-univesp-2022.zip](https://github.com/Takasakiii/notas-univesp-2022/files/8732605/notas-univesp-2022.zip)

caso deseje compilar por si mesmo basta ter o compilador [Rust](https://www.rust-lang.org/pt-BR) e usar o comando `cargo run --release`
